name: Deploy Terraform to AWS

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/deployment.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Deploy Terraform
        uses: enpicie/gh-action-workflow-terraform-run@v0.1.0
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN_TF_INFRA_DEPLOY }}
          state_key: aws-infra/infra.tfstate
          aws_region: us-east-2
